llama_stack:
  base_url: "http://localhost:8321"
  model: "llama3.2:3b"

vector_db:
  id: "iac"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dim: 384
  chunk_size: 512

docs_folder: "docs"

agent_endpoints:
  classifier: "http://localhost:8000/api/classify"
  context: "http://localhost:8000/api/context"
  converter: "http://localhost:8000/api/convert"
  validator: "http://localhost:8000/api/validate"

logging:
  log_dir: "logs"
  file: "agentic_model.log"
  app_log: "app.log"
  level: INFO
